//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace ShikiDesk
{
	/// <summary>
	/// Database       : Filters
	/// Data Source    : Filters
	/// Server Version : 3.14.2
	/// </summary>
	public partial class FiltersDB : LinqToDB.Data.DataConnection
	{
		public ITable<TGenre>     TGenres     { get { return this.GetTable<TGenre>(); } }
		public ITable<TPublisher> TPublishers { get { return this.GetTable<TPublisher>(); } }
		public ITable<TStudio>    TStudios    { get { return this.GetTable<TStudio>(); } }

		public FiltersDB()
		{
			InitDataContext();
		}

		public FiltersDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("Genres")]
	public partial class TGenre
	{
		[PrimaryKey, NotNull    ] public int    id      { get; set; } // int
        [Column,        Nullable] public string name    { get; set; } // string(max)
		[Column,        Nullable] public string russian { get; set; } // string(max)
		[Column,        Nullable] public string kind    { get; set; } // string(max)
	}

	[Table("Publishers")]
	public partial class TPublisher
	{
		[PrimaryKey, NotNull    ] public int    id   { get; set; } // int
		[Column,        Nullable] public string name { get; set; } // string(max)
	}

	[Table("Studios")]
	public partial class TStudio
	{
		[PrimaryKey, NotNull    ] public int    id            { get; set; } // int
		[Column,        Nullable] public string name          { get; set; } // string(max)
		[Column,        Nullable] public string filtered_name { get; set; } // string(max)
		[Column,     NotNull    ] public bool   real          { get; set; } // boolean
		[Column,        Nullable] public string image         { get; set; } // string(max)
	}

	public static partial class TableExtensions
	{
		public static TGenre Find(this ITable<TGenre> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static TPublisher Find(this ITable<TPublisher> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static TStudio Find(this ITable<TStudio> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}
	}
}
