//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace ShikiDesk
{
	/// <summary>
	/// Database       : UserRates
	/// Data Source    : UserRates
	/// Server Version : 3.14.2
	/// </summary>
	public partial class UserRatesDB : LinqToDB.Data.DataConnection
	{
		public ITable<TAnimeRate> TAnimeRates { get { return this.GetTable<TAnimeRate>(); } }
		public ITable<TMangaRate> TMangaRates { get { return this.GetTable<TMangaRate>(); } }

		public UserRatesDB()
		{
			InitDataContext();
		}

		public UserRatesDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("AnimeRates")]
	public partial class TAnimeRate
	{
		[PrimaryKey, NotNull    ] public int    user_rate_id       { get; set; } // int
        [Column,     NotNull    ] public int    title_id           { get; set; } // int
        [Column,        Nullable] public string original_name      { get; set; } // string(max)
		[Column,        Nullable] public string rus_name           { get; set; } // string(max)
		[Column,        Nullable] public string url                { get; set; } // string(max)
		[Column,        Nullable] public string kind               { get; set; } // string(max)
		[Column,        Nullable] public string title_status       { get; set; } // string(max)
		[Column,        Nullable] public string aired_on           { get; set; } // string(max)
		[Column,        Nullable] public string released_on        { get; set; } // string(max)
		[Column,     NotNull    ] public int    total_episodes     { get; set; } // int
        [Column,     NotNull    ] public int    aired_episodes     { get; set; } // int
        [Column,     NotNull    ] public int    completed_episodes { get; set; } // int
        [Column,        Nullable] public string user_status        { get; set; } // string(max)
		[Column,     NotNull    ] public int    score              { get; set; } // int
    }

	[Table("MangaRates")]
	public partial class TMangaRate
	{
		[PrimaryKey, NotNull    ] public int    user_rate_id       { get; set; } // int
        [Column,     NotNull    ] public int    title_id           { get; set; } // int
        [Column,        Nullable] public string original_name      { get; set; } // string(max)
		[Column,        Nullable] public string rus_name           { get; set; } // string(max)
		[Column,        Nullable] public string url                { get; set; } // string(max)
		[Column,        Nullable] public string kind               { get; set; } // string(max)
		[Column,        Nullable] public string title_status       { get; set; } // string(max)
		[Column,        Nullable] public string aired_on           { get; set; } // string(max)
		[Column,        Nullable] public string released_on        { get; set; } // string(max)
		[Column,     NotNull    ] public int    total_volumes      { get; set; } // int
        [Column,     NotNull    ] public int    total_chapters     { get; set; } // int
        [Column,     NotNull    ] public int    completed_volumes  { get; set; } // int
        [Column,     NotNull    ] public int    completed_chapters { get; set; } // int
        [Column,        Nullable] public string user_status        { get; set; } // string(max)
		[Column,     NotNull    ] public int    score              { get; set; } // int
    }

	public static partial class TableExtensions
	{
		public static TAnimeRate Find(this ITable<TAnimeRate> table, int user_rate_id)
		{
			return table.FirstOrDefault(t =>
				t.user_rate_id == user_rate_id);
		}

		public static TMangaRate Find(this ITable<TMangaRate> table, int user_rate_id)
		{
			return table.FirstOrDefault(t =>
				t.user_rate_id == user_rate_id);
		}
	}
}
